name: Build

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - 'release/?*'
      - 'dev'
  schedule:
    - cron: '30 1 * * 6' # Weekly on Saturdays

permissions: {}

jobs:
  call-workflow:
    if: "!contains(github.repository, '.warriors-life-template')"
    uses: warriors-life/.warriors-life-workflows/.github/workflows/build-general.yml@dev
    secrets: inherit
    permissions:
      actions: read
      contents: read
