name: Update release branch from dev in template repository

on:
  push:
    branches:
      - 'dev'

permissions: {}

jobs:
  update-branch:
    if: contains(github.repository, '.warriors-life-template')

    name: Update release branch from dev in template repository

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          fetch-depth: 0

      - name: Update
        run: |
          git checkout release
          git branch -m release dummy
          git branch -m dev release
          git push -f origin release
