name: Update release branch from dev

on:
  push:
    branches:
      - 'dev'

permissions: {}

jobs:
  call-workflow:
    if: contains(github.repository, '.warriors-life-template')
    uses: warriors-life/.warriors-life-workflows/.github/workflows/update-template.yml@dev
    permissions:
      contents: write
